on: [push]
#  schedule:
#    - cron: '0 0 * * 0'

name: Check links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://nanocommons.github.io/handbook/
