on: [push]
#  schedule:
#    - cron: '0 0 * * 0'

name: Check markdown links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://www.google.com
#          url: https://nanocommons.github.io/user-handbook/
          cmd_params: "--one-page-only --max-connections=3 --color=always"  # Check just one page